language: c
sudo: false
git:
  depth: false
  quiet: true
addons:
  apt:
    sources:
    packages:
      - unzip
      - wget
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.10"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:

install:

script:
   - bash build.sh

# Generate and deploy documentation
after_success:

notifications:
  email:
    on_success: change
    on_failure: change
