language: c
sudo: false
git:
  depth: false
  quiet: true
addons:
  apt:
    sources:
    packages:
      - unzip
      - wget
env:
  global:

before_install:

install:

script:
   - bash build.sh

# Generate and deploy documentation
after_success:

notifications:
  email:
    on_success: change
    on_failure: change
